// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuzk70qtp3Dj48EI7r7INI_OFyJzp7oE',
    appId: '1:1092168608128:web:a0773eb7819a0ab126f965',
    messagingSenderId: '1092168608128',
    projectId: 'nghianote-flutter-project',
    authDomain: 'nghianote-flutter-project.firebaseapp.com',
    storageBucket: 'nghianote-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXw_GPq1lPNTPHFYTVUoC9TuX_2nU9Gaw',
    appId: '1:1092168608128:android:a0a6268e6493caff26f965',
    messagingSenderId: '1092168608128',
    projectId: 'nghianote-flutter-project',
    storageBucket: 'nghianote-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQXZxByErpXpQd8pBl6RCYKOwvdltN6Hw',
    appId: '1:1092168608128:ios:34f754159564cb2526f965',
    messagingSenderId: '1092168608128',
    projectId: 'nghianote-flutter-project',
    storageBucket: 'nghianote-flutter-project.appspot.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQXZxByErpXpQd8pBl6RCYKOwvdltN6Hw',
    appId: '1:1092168608128:ios:3cb524dfdcf50f0826f965',
    messagingSenderId: '1092168608128',
    projectId: 'nghianote-flutter-project',
    storageBucket: 'nghianote-flutter-project.appspot.com',
    iosBundleId: 'se.pixolity.mynotes.RunnerTests',
  );
}
